proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from app.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name = 'home'),
    path('about/', about, name='about'),
    path('portfolio/', portfolio, name='portfolio'),
    path('contact/', contact, name='contact'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from PIL import Image
from django.utils.text import slugify

def arabic_slugify(str):
    str = str.replace(" ", "-")
    str = str.replace(",", "-")
    str = str.replace("(", "-")
    str = str.replace(")", "")
    str = str.replace("؟", "")
    return str
# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length=50,verbose_name='الاسم الأول')
    last_name = models.CharField(max_length=50,verbose_name='الاسم الأخير')
    phone = models.CharField(max_length=15,verbose_name='رقم الهاتف ')
    email = models.EmailField(verbose_name='البريد الالكتروني')
    age = models.IntegerField(default=0,verbose_name='العمر')
    content = models.TextField(help_text='من انت ؟!',verbose_name='الوصف')
    address = models.CharField(max_length=10000,verbose_name='العنوان')
    nationality = models.CharField(max_length=50,verbose_name='الجنسيه')
    langages  = models.CharField(max_length=50,verbose_name='اللغات')
    exp = models.IntegerField(default=0,verbose_name='سنين الخبره')
    projects = models.IntegerField(default=0,verbose_name='المشاريع المكتمله')
    image = models.ImageField(default='img-mobile.jpg', upload_to='profile_pics',help_text='يفضل ان تكون بحجم 300x300',verbose_name='صورة الملف الشخصي')
    def __str__(self):
        return self.first_name+' '+self.last_name
    class Meta:
        verbose_name = ('الملف الشخصي')
        verbose_name_plural = ('الملف الشخصي')

class Portfolio(models.Model):
    title = models.CharField(max_length=1000,verbose_name='عنوان المشروع')
    cat = models.CharField(max_length=100,help_text='قم باختيار نوع التصميم لوجو او بانر ...الخ',verbose_name='نوع المشروع')
    client = models.CharField(max_length=1000,verbose_name='العميل/الزبون')
    skills = models.CharField(max_length=1000,verbose_name='المهارات المستخدمه')
    link = models.URLField(blank=True,null=True, verbose_name= 'رابط المشروع ان وجد')
    file = models.ImageField(help_text='قم باختيار صورة التصميم من جهازك',verbose_name='ملف المشروع')
    slug = models.SlugField(blank=True,null=True,unique=True,allow_unicode=True,editable=False)
    date = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            if not self.slug:
                self.slug = arabic_slugify(self.title)
        super(Portfolio, self).save(*args, **kwargs)
    class Meta:
        verbose_name = ('مشروع ')
        verbose_name_plural = ('المشاريع/Portfolio')
        ordering = ('-date',)
class Contact(models.Model):
    name = models.CharField(max_length= 100 , verbose_name='الاسم')
    sub = models.CharField(max_length= 100 , verbose_name='الموضوع')
    email = models.EmailField(verbose_name='البريد الالكتروني')
    message = models.TextField(verbose_name='الرساله')
    date = models.DateTimeField(auto_now=True,verbose_name='تاريخ الاضافه')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = ('رساله')
        verbose_name_plural = ('الرسائل')
        ordering = ('-date',)

app/forms.py
from django import forms
from .models import *

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name',
                  'sub',
                  'message',
                  'email']

app/views.py
from django.shortcuts import render
from django.shortcuts import render,get_object_or_404
from .models import *
from .forms import *
# Create your views here.

def home(request):
    profile = get_object_or_404(Profile)
    full_name =str( profile.first_name +' '+ profile.last_name).upper()

    return render(request,'home.html',context={'title':full_name,'profile':profile})
def about(request):
    profile = get_object_or_404(Profile)
    full_name =str( profile.first_name +' '+ profile.last_name).upper()

    return render(request,'about.html',context={'title':'about','profile':profile})
def portfolio(request):
    proj = Portfolio.objects.all()
    return render(request,'portfolio.html',context={'title':'portfolio','proj':proj})
def contact(request):
    profile = get_object_or_404(Profile)
    if request.method == 'POST':
        comment_form = ContactForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.save()
            comment_form = ContactForm()
    else:
        comment_form = ContactForm()
    return render(request,'contact.html',context={'title':'contact','profile':profile,'form':comment_form})

app/templates/about.html
{% load static %}

<html lang="en" style="" class=" js csstransforms3d csstransitions">
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link href="http://slimhamdi.net/tunis/dark/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/preloader.min.css" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/circle.css" rel="stylesheet">
    <link href="{% static 'font-awesome.min.css' %}" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/fm.revealator.jquery.min.css" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/style.css" rel="stylesheet">

    <!-- CSS Skin File -->

    <!-- Live Style Switcher - demo only -->
    <link rel=" stylesheet" type="text/css" title="blue" href="  http://slimhamdi.net/tunis/dark/css/skins/blue.css">
    <link rel="stylesheet" type="text/css" href="http://slimhamdi.net/tunis/dark/css/styleswitcher.css">

    <!-- Modernizr JS File -->
    <script src="http://slimhamdi.net/tunis/dark/js/modernizr.custom.js"></script>
</head>

<body class="about" data-new-gr-c-s-check-loaded="14.991.0" data-gr-ext-installed=""><div id="preloader" class="preloader off"><div class="black_wall"></div><div class="loader"></div></div>
<!-- Live Style Switcher Starts - demo only -->
<div id="switcher" class="">
    <div class="content-switcher">
        <h4>STYLE SWITCHER</h4>
        <ul>
            <li>
                <a href="#" onclick="setActiveStyleSheet('purple');" title="purple" class="color"><img src="img/styleswitcher/purple.png" alt="purple"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('red');" title="red" class="color"><img src="img/styleswitcher/red.png" alt="red"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blueviolet');" title="blueviolet" class="color"><img src="img/styleswitcher/blueviolet.png" alt="blueviolet"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blue');" title="blue" class="color"><img src="img/styleswitcher/blue.png" alt="blue"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('goldenrod');" title="goldenrod" class="color"><img src="img/styleswitcher/goldenrod.png" alt="goldenrod"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('magenta');" title="magenta" class="color"><img src="img/styleswitcher/magenta.png" alt="magenta"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellowgreen');" title="yellowgreen" class="color"><img src="img/styleswitcher/yellowgreen.png" alt="yellowgreen"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('orange');" title="orange" class="color"><img src="img/styleswitcher/orange.png" alt="orange"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('green');" title="green" class="color"><img src="img/styleswitcher/green.png" alt="green"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellow');" title="yellow" class="color"><img src="img/styleswitcher/yellow.png" alt="yellow"></a>
            </li>
        </ul>

        <a href="https://themeforest.net/item/tunis-personal-portfolio/26761598?irgwc=1&amp;clickid=UBs0rDX6YxyJWfewUx0Mo3E1UkiwozXD10XATw0&amp;iradid=275988&amp;irpid=1327395&amp;iradtype=ONLINE_TRACKING_LINK&amp;irmptype=mediapartner&amp;mp_value1=&amp;utm_campaign=af_impact_radius_1327395&amp;utm_medium=affiliate&amp;utm_source=impact_radius" class="waves-effect waves-light font-weight-700 purchase"><i class="fa fa-shopping-cart"></i> Purchase</a>
        <div id="hideSwitcher">×</div>
    </div>
</div>

<!-- Live Style Switcher Ends - demo only -->
<!-- Header Starts -->
<header class="header" id="navbar-collapse-toggle">
    <!-- Fixed Navigation Starts -->
    <ul class="icon-menu d-none d-lg-block revealator-slideup revealator-once revealator-delay1 no-transform revealator-within">
        <li class="icon-box">
            <i class="fa fa-home"></i>
            <a href="/">
                <h2>Home</h2>
            </a>
        </li>
        <li class="icon-box active">
            <i class="fa fa-user"></i>
            <a href="/about">
                <h2>About</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-briefcase"></i>
            <a href="/portfolio">
                <h2>Portfolio</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-envelope-open"></i>
            <a href="/contact">
                <h2>Contact</h2>
            </a>
        </li>
    </ul>
    <!-- Fixed Navigation Ends -->
    <!-- Mobile Menu Starts -->
    <nav role="navigation" class="d-block d-lg-none">
        <div id="menuToggle">
            <input type="checkbox">
            <span></span>
            <span></span>
            <span></span>
            <ul class="list-unstyled" id="menu">
                <li><a href="/"><i class="fa fa-home"></i><span>Home</span></a></li>
                <li class="active"><a href="/about"><i class="fa fa-user"></i><span>About</span></a></li>
                <li><a href="/portfolio"><i class="fa fa-folder-open"></i><span>Portfolio</span></a></li>
                <li><a href="/contact"><i class="fa fa-envelope-open"></i><span>Contact</span></a></li>
            </ul>
        </div>
    </nav>
    <!-- Mobile Menu Ends -->
</header>
<!-- Header Ends -->
<!-- Page Title Starts -->
<section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1 no-transform revealator-within">
    <h1>ABOUT <span>ME</span></h1>
    <span class="title-bg">Resume</span>
</section>
<!-- Page Title Ends -->
<!-- Main Content Starts -->
<section class="main-content revealator-slideup revealator-once revealator-delay1 no-transform revealator-partially-above revealator-within">
    <div class="container">
        <div class="row">
            <!-- Personal Info Starts -->
            <div class="col-12 col-lg-5 col-xl-6">
                <div class="row">
                    <div class="col-12">
                        <h3 class="text-uppercase custom-title mb-0 ft-wt-600">personal infos</h3>
                    </div>
                    <div class="col-12 d-block d-sm-none">
                        <img src="{{ profile.image.url }}" class="img-fluid main-img-mobile" alt="my picture">
                    </div>
                    <div class="col-6">
                        <ul class="about-list list-unstyled open-sans-font">
                            <li> <span class="title">first name :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{ profile.first_name }}</span> </li>
                            <li> <span class="title">last name :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{ profile.last_name }}</span> </li>
                            <li> <span class="title">Age :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{ profile.age }} Years</span> </li>
                            <li> <span class="title">Nationality :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{ profile.nationality }}</span> </li>
                        </ul>
                    </div>
                    <div class="col-6">
                        <ul class="about-list list-unstyled open-sans-font">
                            <li> <span class="title">Address :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{ profile.address }}</span> </li>
                            <li> <span class="title">phone :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">+{{ profile.phone }}</span> </li>
                            <li> <span class="title">Email :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{ profile.email }}</span> </li>
                            <li> <span class="title">langages :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{ profile.langages }}</span> </li>
                        </ul>
                    </div>
                    <div class="col-12 mt-3">
                        <a href="#" class="btn btn-download"><span data-hover="Download CV">Download CV</span></a>
                    </div>
                </div>
            </div>
            <!-- Personal Info Ends -->
            <!-- Boxes Starts -->
            <div class="col-12 col-lg-7 col-xl-6 mt-5 mt-lg-0">
                <div class="row">
                    <div class="col-6">
                        <div class="box-stats with-margin">
                            <h3 class="poppins-font position-relative">{{ profile.exp }}</h3>
                            <p class="open-sans-font m-0 position-relative text-uppercase">years of <span class="d-block">experience</span></p>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="box-stats with-margin">
                            <h3 class="poppins-font position-relative">{{ profile.projects }}</h3>
                            <p class="open-sans-font m-0 position-relative text-uppercase">completed <span class="d-block">projects</span></p>
                        </div>
                    </div>
                    <div class="col-6">

                    </div>
                    <div class="col-6">

                    </div>
                </div>
            </div>
            <!-- Boxes Ends -->
        </div>
        <hr class="separator">
        <!-- Skills Starts -->
        <div class="row">
            <div class="col-12">
                <h3 class="text-uppercase pb-4 pb-sm-5 mb-3 mb-sm-0 text-left text-sm-center custom-title ft-wt-600">My Skills</h3>
            </div>




            <div class="col-6 col-md-3 mb-3 mb-sm-5">
                <div class="c100 p99">
                    <span>99%</span>
                    <div class="slice">
                        <div class="bar"></div>
                        <div class="fill"></div>
                    </div>
                </div>
                <h6 class="text-uppercase open-sans-font text-center mt-2 mt-sm-4">Illustrator</h6>
            </div>
            <div class="col-6 col-md-3 mb-3 mb-sm-5">
                <div class="c100 p80">
                    <span>80%</span>
                    <div class="slice">
                        <div class="bar"></div>
                        <div class="fill"></div>
                    </div>
                </div>
                <h6 class="text-uppercase open-sans-font text-center mt-2 mt-sm-4">Photoshop</h6>
            </div>
            <div class="col-6 col-md-3 mb-3 mb-sm-5">
                <div class="c100 p70">
                    <span>70%</span>
                    <div class="slice">
                        <div class="bar"></div>
                        <div class="fill"></div>
                    </div>
                </div>
                <h6 class="text-uppercase open-sans-font text-center mt-2 mt-sm-4">UI/UX</h6>
            </div>
            <div class="col-6 col-md-3 mb-3 mb-sm-5">
                <div class="c100 p85">
                    <span>85%</span>
                    <div class="slice">
                        <div class="bar"></div>
                        <div class="fill"></div>
                    </div>
                </div>
                <h6 class="text-uppercase open-sans-font text-center mt-2 mt-sm-4">InDesign</h6>
            </div>
        </div>
        <!-- Skills Ends -->
        <hr class="separator mt-1">
        <!-- Experience & Education Starts -->
        <div class="row">
            <div class="col-12">

            </div>


        </div>
        <!-- Experience & Education Ends -->
    </div>
</section>
<!-- Main Content Ends -->

<!-- Template JS Files -->
<script src="http://slimhamdi.net/tunis/dark/js/jquery-3.5.0.min.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/styleswitcher.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/preloader.min.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/fm.revealator.jquery.min.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/imagesloaded.pkgd.min.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/masonry.pkgd.min.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/classie.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/cbpGridGallery.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/jquery.hoverdir.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/popper.min.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/bootstrap.js"></script>
<script src="http://slimhamdi.net/tunis/dark/js/custom.js"></script>
<script src="https://kit.fontawesome.com/70eebe618b.js" crossorigin="anonymous"></script>




</body></html>

app/templates/contact.html
{% load static %}

<html lang="en" style="" class=" js csstransforms3d csstransitions">
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link href="http://slimhamdi.net/tunis/dark/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/preloader.min.css" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/circle.css" rel="stylesheet">
    <link href="{% static 'font-awesome.min.css' %}" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/fm.revealator.jquery.min.css" rel="stylesheet">
    <link href="http://slimhamdi.net/tunis/dark/css/style.css" rel="stylesheet">

    <!-- CSS Skin File -->

    <!-- Live Style Switcher - demo only -->
    <link rel=" stylesheet" type="text/css" title="blue" href="  http://slimhamdi.net/tunis/dark/css/skins/blue.css">
    <link rel="stylesheet" type="text/css" href="http://slimhamdi.net/tunis/dark/css/styleswitcher.css">

    <!-- Modernizr JS File -->
    <script src="http://slimhamdi.net/tunis/dark/js/modernizr.custom.js"></script>
</head>

<body class="contact at-top" data-new-gr-c-s-check-loaded="14.991.0" data-gr-ext-installed=""><div id="preloader" class="preloader off"><div class="black_wall"></div><div class="loader"></div></div>
<!-- Live Style Switcher Starts - demo only -->
<div id="switcher" class="">
    <div class="content-switcher">
        <h4>STYLE SWITCHER</h4>
        <ul>
            <li>
                <a href="#" onclick="setActiveStyleSheet('purple');" title="purple" class="color"><img src="img/styleswitcher/purple.png" alt="purple"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('red');" title="red" class="color"><img src="img/styleswitcher/red.png" alt="red"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blueviolet');" title="blueviolet" class="color"><img src="img/styleswitcher/blueviolet.png" alt="blueviolet"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blue');" title="blue" class="color"><img src="img/styleswitcher/blue.png" alt="blue"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('goldenrod');" title="goldenrod" class="color"><img src="img/styleswitcher/goldenrod.png" alt="goldenrod"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('magenta');" title="magenta" class="color"><img src="img/styleswitcher/magenta.png" alt="magenta"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellowgreen');" title="yellowgreen" class="color"><img src="img/styleswitcher/yellowgreen.png" alt="yellowgreen"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('orange');" title="orange" class="color"><img src="img/styleswitcher/orange.png" alt="orange"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('green');" title="green" class="color"><img src="img/styleswitcher/green.png" alt="green"></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellow');" title="yellow" class="color"><img src="img/styleswitcher/yellow.png" alt="yellow"></a>
            </li>
        </ul>

        <a href="https://themeforest.net/item/tunis-personal-portfolio/26761598?irgwc=1&amp;clickid=UBs0rDX6YxyJWfewUx0Mo3E1UkiwozXD10XATw0&amp;iradid=275988&amp;irpid=1327395&amp;iradtype=ONLINE_TRACKING_LINK&amp;irmptype=mediapartner&amp;mp_value1=&amp;utm_campaign=af_impact_radius_1327395&amp;utm_medium=affiliate&amp;utm_source=impact_radius" class="waves-effect waves-light font-weight-700 purchase"><i class="fa fa-shopping-cart"></i> Purchase</a>
        <div id="hideSwitcher">×</div>
    </div>
</div>

<!-- Live Style Switcher Ends - demo only -->
<!-- Header Starts -->
<header class="header" id="navbar-collapse-toggle">
    <!-- Fixed Navigation Starts -->
    <ul class="icon-menu d-none d-lg-block revealator-slideup revealator-once revealator-delay1 no-transform revealator-within">
        <li class="icon-box">
            <i class="fa fa-home"></i>
            <a href="/">
                <h2>Home</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-user"></i>
            <a href="/about">
                <h2>About</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-briefcase"></i>
            <a href="/portfolio">
                <h2>Portfolio</h2>
            </a>
        </li>
        <li class="icon-box active">
            <i class="fa fa-envelope-open"></i>
            <a href="/contact">
                <h2>Contact</h2>
            </a>
        </li>

    </ul>
    <!-- Fixed Navigation Ends -->
    <!-- Mobile Menu Starts -->
    <nav role="navigation" class="d-block d-lg-none">
        <div id="menuToggle">
            <input type="checkbox">
            <span></span>
            <span></span>
            <span></span>
            <ul class="list-unstyled" id="menu">
                <li><a href="/"><i class="fa fa-home"></i><span>Home</span></a></li>
                <li><a href="/about"><i class="fa fa-user"></i><span>About</span></a></li>
                <li><a href="/portfolio"><i class="fa fa-folder-open"></i><span>Portfolio</span></a></li>
                <li class="active"><a href="/contact"><i class="fa fa-envelope-open"></i><span>Contact</span></a></li>
                <li></li>
            </ul>
        </div>
    </nav>
    <!-- Mobile Menu Ends -->
</header>
<!-- Header Ends -->
<!-- Page Title Starts -->
<section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1 no-transform revealator-within">
    <h1>get in <span>touch</span></h1>
    <span class="title-bg">contact</span>
</section>
<!-- Page Title Ends -->
<!-- Main Content Starts -->
<section class="main-content revealator-slideup revealator-once revealator-delay1 no-transform revealator-within">
    <div class="container">
        <div class="row">
            <!-- Left Side Starts -->
            <div class="col-12 col-lg-4">
                <h3 class="text-uppercase custom-title mb-0 ft-wt-600 pb-3">Don't be shy !</h3>
                <p class="open-sans-font mb-3">Feel free to get in touch with me. I am always open to discussing new projects, creative ideas or opportunities to be part of your visions.</p>
                <p class="open-sans-font custom-span-contact position-relative">
                    <i class="fa fa-envelope-open position-absolute"></i>
                    <span class="d-block">mail me</span>{{ profile.email }}
                </p>
                <p class="open-sans-font custom-span-contact position-relative">
                    <i class="fa fa-phone-square position-absolute"></i>
                    <span class="d-block">call me</span>{{ profile.phone }}
                </p>
                <ul class="social list-unstyled pt-1 mb-5">
                    <li class="facebook"><a title="Facebook" href="https://www.facebook.com/mhmd.yasser.77"><i style="margin-top: 11px;" class="fa fa-facebook"></i></a>
                    </li>
                   <li class="instagram"><a title="instagram" href="https://www.instagram.com/mhmd.yasserr/"><i style="margin-top: 11px;" class="fa fa-instagram"></i></a>

                    <li class="whatsapp"><a title="whatsapp" href="https://api.whatsapp.com/send/?phone=+201153274828"><i style="margin-top: 11px;" class="fa fa-whatsapp"></i></a>
                    </li>
                    <li class="youtube"><a title="Youtube" href="https://www.youtube.com/channel/UCgAie0r3yeXmLlpfTwE-DXA"><i style="margin-top: 11px;" class="fa fa-youtube"></i></a>
                    </li>
                    </li>
                </ul>
            </div>
            <!-- Left Side Ends -->
            <!-- Contact Form Starts -->
            <div class="col-12 col-lg-8">
                <form class="contactform" method="POST" >
                                                                {% csrf_token %}

                    <div class="contactform">
                        <div class="row">
                            <div class="col-12 col-md-4">
                                <input id="id_name" maxlength="100" required type="text" name="name" placeholder="YOUR NAME">
                            </div>
                            <div class="col-12 col-md-4">
                                <input id="id_email" required type="email" name="email" placeholder="YOUR EMAIL">
                            </div>
                            <div class="col-12 col-md-4">
                                <input id="id_sub" maxlength="100" required type="text" name="subject" placeholder="YOUR SUBJECT">
                            </div>
                            <div class="col-12">
                                <textarea id="id_message" required name="message" placeholder="YOUR MESSAGE"></textarea>
                                <button type="submit" class="btn btn-contact"><span data-hover="Send Message">Send Message</span></button>
                            </div>
                            <div class="col-12 form-message">
                                <span class="output_message text-center font-weight-600 text-uppercase"></span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- Contact Form Ends -->
        </div>
    </div>

</section>
<!-- Template JS Files -->

<script src="https://kit.fontawesome.com/70eebe618b.js" crossorigin="anonymous"></script>



</body>
</html>